[package]
name = "rs-uploader"
version = "0.1.0"
edition = "2021"

[dependencies]
rust-s3 = { version = "0.28", default-features = false, features = [
    "sync",
    "sync-native-tls",
] }
chrono = "0.4"
load-dotenv = "0.1"
nanoid = "0.4.0"
